@BASE_URL = "http://localhost:5001"



###############################################################################
# This should return "Hello.", plain text.

GET {{BASE_URL}}/ HTTP/1.1



###############################################################################
# This should return "Hello, <NAME>.", plain text.
# @prompt NAME

GET {{BASE_URL}}/{{NAME}} HTTP/1.1
